In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('Bengaluru_House_Data.csv')
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [5]:
df.shape

(13320, 9)

In [7]:
df['area_type'].value_counts()

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64

In [9]:
df['availability'].value_counts()

availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
15-Aug               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64

In [10]:
df['balcony'].value_counts()

balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64

In [11]:
df['bath'].value_counts()

bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
13.0       3
11.0       3
16.0       2
27.0       1
40.0       1
15.0       1
14.0       1
18.0       1
Name: count, dtype: int64

In [12]:
df['location'].value_counts()

location
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64

In [13]:
df['price'].value_counts()

price
75.00     310
65.00     302
55.00     275
60.00     270
45.00     240
         ...
351.00      1
54.10       1
80.64       1
32.73       1
488.00      1
Name: count, Length: 1994, dtype: int64

In [14]:
df['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [15]:
df['society'].value_counts()

society
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
Amionce     1
JaghtDe     1
Jauraht     1
Brity U     1
RSntsAp     1
Name: count, Length: 2688, dtype: int64

In [16]:
df['total_sqft'].value_counts()

total_sqft
1200    843
1100    221
1500    205
2400    196
600     180
       ...
3580      1
2461      1
1437      1
2155      1
4689      1
Name: count, Length: 2117, dtype: int64

In [17]:
df.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [18]:
df.drop(columns=['area_type','availability','society','balcony'],inplace=True)

In [19]:
df.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [21]:
df['location']=df['location'].fillna('Sarjapur Road')

In [22]:
df['size']=df['size'].fillna('2 BHK')

In [23]:
df['bath']=df['bath'].fillna(df['bath'].median())

In [24]:
df.isna().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [26]:
df['bhk']=df['size'].str.split().str.get(0).astype(int)

In [27]:
df[df['bhk']>20]

                       location        size total_sqft  bath  price  bhk
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [28]:
df['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(2117,), dtype=object)

In [29]:
def rangeConverter(x):
    t=x.split('-')
    if len(t)==2:
        return (float(t[0])+float(t[1]))/2
    try:
        return float(x)
    except:
        return None

In [30]:
df['total_sqft']=df['total_sqft'].apply(rangeConverter)

In [31]:
df.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

In [32]:
df['price_per_sft']=df['price']*100000 / df['total_sqft']
df['price_per_sft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sft, Length: 13320, dtype: float64

In [33]:
df.describe()

         total_sqft          bath         price           bhk  price_per_sft
count  13274.000000  13320.000000  13320.000000  13320.000000   1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778   7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496   1.064296e+05
min        1.000000      1.000000      8.000000      1.000000   2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000   4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000   5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000   7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000   1.200000e+07

In [34]:
df['location'].value_counts()

location
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Uvce Layout                         1
Abshot Layout                       1
Name: count, Length: 1306, dtype: int64

In [35]:
df['location']=df['location'].apply(lambda x:x.strip())
loc_cnt=df['location'].value_counts()

In [36]:
locCnt_lessThan10=loc_cnt[loc_cnt<=10]
locCnt_lessThan10

location
BTM 1st Stage                         10
Nagadevanahalli                       10
Basapura                              10
Sector 1 HSR Layout                   10
Dairy Circle                          10
                                      ..
1Channasandra                          1
Hosahalli                              1
Vijayabank bank layout                 1
near Ramanashree California resort     1
Abshot Layout                          1
Name: count, Length: 1054, dtype: int64

In [37]:
df['location']=df['location'].apply(lambda x: 'Other' if x in locCnt_lessThan10 else x)

In [38]:
df.describe()

         total_sqft          bath         price           bhk  price_per_sft
count  13274.000000  13320.000000  13320.000000  13320.000000   1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778   7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496   1.064296e+05
min        1.000000      1.000000      8.000000      1.000000   2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000   4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000   5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000   7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000   1.200000e+07

In [39]:
(df['total_sqft']/df['bhk']).describe()

count    13274.000000
mean       575.074878
std        388.205175
min          0.250000
25%        473.333333
50%        552.500000
75%        625.000000
max      26136.000000
dtype: float64

In [40]:
df=df[((df['total_sqft']/df['bhk'])>=300)]
df.describe()

         total_sqft          bath         price           bhk  price_per_sft
count  12530.000000  12530.000000  12530.000000  12530.000000   12530.000000
mean    1594.564544      2.559537    111.382401      2.650838    6303.979357
std     1261.271296      1.077938    152.077329      0.976678    4162.237981
min      300.000000      1.000000      8.440000      1.000000     267.829813
25%     1116.000000      2.000000     49.000000      2.000000    4210.526316
50%     1300.000000      2.000000     70.000000      3.000000    5294.117647
75%     1700.000000      3.000000    115.000000      3.000000    6916.666667
max    52272.000000     16.000000   3600.000000     16.000000  176470.588235

In [41]:
df.shape

(12530, 7)

In [42]:
def sft_outliers_removal(df):
    out=pd.DataFrame()
    for key,subdf in df.groupby('location'):
        mn=np.mean(subdf.price_per_sft)
        sd=np.std(subdf.price_per_sft)
        gen_df=subdf[(subdf.price_per_sft>(mn-sd))&(subdf.price_per_sft<=(mn+sd))]
        out=pd.concat([out,gen_df],ignore_index=True)
    return out
df=sft_outliers_removal(df)
df.describe()

         total_sqft          bath         price           bhk  price_per_sft
count  10301.000000  10301.000000  10301.000000  10301.000000   10301.000000
mean    1508.440608      2.471702     91.286372      2.574896    5659.062876
std      880.694214      0.979449     86.342786      0.897649    2265.774749
min      300.000000      1.000000     10.000000      1.000000    1250.000000
25%     1110.000000      2.000000     49.000000      2.000000    4244.897959
50%     1286.000000      2.000000     67.000000      2.000000    5175.600739
75%     1650.000000      3.000000    100.000000      3.000000    6428.571429
max    30400.000000     16.000000   2200.000000     16.000000   24509.803922

In [44]:
def remove_bhk_outliers(df):
    excludeIndices=np.array([])
    for loc,locdf in df.groupby('location'):
        bhk_stats={}
        for bhk,bhkdf in locdf.groupby('bhk'):
            bhk_stats[bhk]={
                'mean':np.mean(bhkdf.price_per_sft),
                'std':np.std(bhkdf.price_per_sft),
                'count':bhkdf.shape[0]
            }
        for bhk,bhkdf in locdf.groupby('bhk'):
            stats=bhk_stats.get(bhk-1)
            if stats and stats['count']>5:
                excludeIndices=np.append(excludeIndices,bhkdf[bhkdf.price_per_sft<(stats['mean'])].index.values)
    return df.drop(excludeIndices,axis='index')

In [45]:
df=remove_bhk_outliers(df)

In [46]:
df.shape

(7361, 7)

In [47]:
df

,location,size,total_sqft,bath,price,bhk,price_per_sft
0,1st Block Jayanagar,4 BHK,2850.0,4.0,428.0,4,15017.543860
1,1st Block Jayanagar,3 BHK,1630.0,3.0,194.0,3,11901.840491
2,1st Block Jayanagar,3 BHK,1875.0,2.0,235.0,3,12533.333333
3,1st Block Jayanagar,3 BHK,1200.0,2.0,130.0,3,10833.333333
4,1st Block Jayanagar,2 BHK,1235.0,2.0,148.0,2,11983.805668
...,...,...,...,...,...,...,...
10290,Yeshwanthpur,2 BHK,1195.0,2.0,100.0,2,8368.200837
10291,Yeshwanthpur,3 BHK,1692.0,3.0,108.0,3,6382.978723
10293,Yeshwanthpur,6 Bedroom,2500.0,5.0,185.0,6,7400.000000
10298,Yeshwanthpur,3 BHK,1855.0,3.0,135.0,3,7277.628032
10299,Yeshwanthpur,3 BHK,1876.0,3.0,160.0,3,8528.784648

In [48]:
df.drop(columns=['size','price_per_sft'],inplace=True)

In [49]:
df.head()

              location  total_sqft  bath  price  bhk
0  1st Block Jayanagar      2850.0   4.0  428.0    4
1  1st Block Jayanagar      1630.0   3.0  194.0    3
2  1st Block Jayanagar      1875.0   2.0  235.0    3
3  1st Block Jayanagar      1200.0   2.0  130.0    3
4  1st Block Jayanagar      1235.0   2.0  148.0    2

In [50]:
df.to_csv('cleaned_data.csv')

In [51]:
X=df.drop(columns=['price'])
y=df['price']

In [52]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [53]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [54]:
print(X_train.shape)
print(X_test.shape)

(5888, 4)
(1473, 4)

In [55]:
coltr=make_column_transformer((OneHotEncoder(sparse_output=False),['location']),remainder='passthrough')

In [56]:
sc=StandardScaler()

In [58]:
lr=LinearRegression()
p=make_pipeline(coltr,sc,lr)
p.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [59]:
yplr=p.predict(X_test)
r2_score(y_test,yplr)

0.8644830688846301

In [65]:
l=Lasso()
pi=make_pipeline(coltr,sc,l)
pi.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [66]:
ypl=pi.predict(X_test)
r2_score(y_test,ypl)

0.8521003264514659

In [67]:
r=Ridge()
pip=make_pipeline(coltr,sc,r)
pip.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [68]:
ypr=pip.predict(X_test)
r2_score(y_test,ypr)

0.864480470820115

In [69]:
print(r2_score(y_test,yplr))
print(r2_score(y_test,ypl))
print(r2_score(y_test,ypr))

0.8644830688846301
0.8521003264514659
0.864480470820115

In [70]:
import pickle
pickle.dump(pip,open('ridgeModel.pkl','wb'))